import * as React from "react";

import { type VariantProps, cva } from "class-variance-authority";
import {
  Activity,
  AlertCircle,
  Apple,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  Axe,
  Banana,
  Banknote,
  BarChart,
  Battery,
  BatteryLow,
  Beer,
  Bell,
  Bike,
  Bird,
  Bluetooth,
  Bomb,
  Bookmark,
  BookmarkPlus,
  Brush,
  Bug,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  CreditCard as Card,
  Carrot,
  Cat,
  Check,
  CheckCircle,
  Cherry,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Cloud,
  CloudRain,
  CloudSnow,
  Coffee,
  Comet,
  Compass,
  Compass as CompassTool,
  Copy,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Dog,
  DollarSign,
  Download,
  Drill,
  Droplets,
  Globe as Earth,
  Edit,
  ExternalLink,
  Eye,
  File,
  FileText,
  Filter,
  Fish,
  Flag,
  Flame,
  Flower,
  Folder,
  FolderOpen,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  Globe,
  Grape,
  Hammer,
  Heart,
  HelpCircle,
  Home,
  IceCream,
  Image,
  Info,
  Key,
  Laptop,
  Leaf,
  Zap as Lightning,
  LineChart,
  Loader2,
  Lock,
  type LucideIcon,
  Moon as Lunar,
  Mail,
  Map,
  MapPin,
  Maximize,
  Medal,
  Menu,
  MessageCircle,
  Mic,
  MicOff,
  Minimize,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  Navigation,
  Palette,
  Pause,
  Phone,
  Pickaxe,
  PieChart,
  Pizza,
  Plane,
  Play,
  Plus,
  Pulse,
  Puzzle,
  Rabbit,
  Receipt,
  RefreshCw,
  Rocket,
  Route,
  Ruler,
  Satellite,
  Saw,
  Scissors,
  Scope,
  Screwdriver,
  Search,
  Seedling,
  Server,
  Settings,
  Share,
  Shield,
  Shield as ShieldIcon,
  Ship,
  ShoppingCart,
  Shovel,
  Signal,
  Smartphone,
  Snowflake,
  Sparkles,
  Star,
  Star as StarIcon,
  Strawberry,
  Sun,
  Sun as Sunny,
  Sword,
  Tablet,
  Tag,
  Target,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Tornado,
  Train,
  Trash,
  Tree,
  TrendingUp,
  Trophy,
  Truck,
  Turtle,
  Unlock,
  Upload,
  UserCheck,
  Users,
  Utensils,
  Video,
  VideoOff,
  Volcano,
  Volume2,
  VolumeX,
  Walk,
  Wand2,
  Watch,
  Waves,
  Wifi,
  WifiOff,
  Wind,
  Wine,
  Wrench,
  X,
  XCircle,
  Zap,
} from "lucide-react";

import { cn } from "@/lib/utils";

const iconVariants = cva("inline-flex items-center justify-center", {
  variants: {
    variant: {
      default: "text-current",
      primary: "text-primary",
      secondary: "text-secondary",
      muted: "text-muted-foreground",
      accent: "text-accent-foreground",
      destructive: "text-destructive",
      success: "text-green-600 dark:text-green-400",
      warning: "text-yellow-600 dark:text-yellow-400",
      info: "text-blue-600 dark:text-blue-400",
    },
    size: {
      xs: "h-3 w-3",
      sm: "h-4 w-4",
      default: "h-5 w-5",
      lg: "h-6 w-6",
      xl: "h-8 w-8",
      "2xl": "h-10 w-10",
    },
  },
  defaultVariants: {
    variant: "default",
    size: "default",
  },
});

export interface IconProps
  extends React.HTMLAttributes<SVGElement>,
    VariantProps<typeof iconVariants> {
  name: keyof typeof iconMap;
}

const iconMap = {
  // Business & Organization
  building: Building2,
  calendar: Calendar,
  checkCircle: CheckCircle,
  clock: Clock,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  eye: Eye,
  fileText: FileText,
  globe: Globe,
  mapPin: MapPin,
  phone: Phone,
  star: Star,
  tag: Tag,
  trendingUp: TrendingUp,
  userCheck: UserCheck,
  users: Users,
  x: X,
  xCircle: XCircle,

  // Navigation & Actions
  search: Search,
  filter: Filter,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash: Trash,
  download: Download,
  upload: Upload,
  settings: Settings,
  menu: Menu,
  home: Home,
  mail: Mail,
  bell: Bell,

  // Social & Communication
  heart: Heart,
  share: Share,
  messageCircle: MessageCircle,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,

  // Media Controls
  play: Play,
  pause: Pause,
  volume2: Volume2,
  volumeX: VolumeX,
  maximize: Maximize,
  minimize: Minimize,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,

  // Arrows & Directions
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  externalLink: ExternalLink,

  // Status & Feedback
  copy: Copy,
  check: Check,
  alertCircle: AlertCircle,
  info: Info,
  helpCircle: HelpCircle,
  loader2: Loader2,
  refreshCw: RefreshCw,

  // Security & System
  zap: Zap,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  database: Database,
  server: Server,
  cloud: Cloud,

  // Connectivity
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  battery: Battery,
  batteryLow: BatteryLow,
  signal: Signal,

  // Devices
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  tablet: Tablet,
  watch: Watch,
  camera: Camera,
  mic: Mic,
  micOff: MicOff,
  video: Video,
  videoOff: VideoOff,

  // Files & Storage
  image: Image,
  file: File,
  folder: Folder,
  folderOpen: FolderOpen,
  archive: Archive,
  bookmark: Bookmark,
  bookmarkPlus: BookmarkPlus,
  flag: Flag,

  // Achievement & Rewards
  award: Award,
  gift: Gift,
  trophy: Trophy,
  medal: Medal,
  crown: Crown,
  gem: Gem,
  sparkles: Sparkles,

  // Commerce
  shoppingCart: ShoppingCart,
  card: Card,
  banknote: Banknote,
  receipt: Receipt,
  calculator: Calculator,

  // Charts & Analytics
  pieChart: PieChart,
  barChart: BarChart,
  lineChart: LineChart,
  activity: Activity,
  pulse: Pulse,
  gauge: Gauge,

  // Weather & Environment
  thermometer: Thermometer,
  droplets: Droplets,
  sun: Sun,
  moon: Moon,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  wind: Wind,

  // Location & Navigation
  compass: Compass,
  navigation: Navigation,
  map: Map,
  route: Route,

  // Transportation
  car: Car,
  truck: Truck,
  bus: Bus,
  train: Train,
  plane: Plane,
  ship: Ship,
  bike: Bike,
  walk: Walk,

  // Food & Drink
  coffee: Coffee,
  pizza: Pizza,
  utensils: Utensils,
  wine: Wine,
  beer: Beer,
  iceCream: IceCream,
  cake: Cake,
  apple: Apple,
  grape: Grape,
  cherry: Cherry,
  strawberry: Strawberry,
  banana: Banana,
  carrot: Carrot,

  // Nature
  leaf: Leaf,
  tree: Tree,
  flower: Flower,
  seedling: Seedling,
  bug: Bug,
  fish: Fish,
  bird: Bird,
  cat: Cat,
  dog: Dog,
  rabbit: Rabbit,
  turtle: Turtle,

  // Gaming & Entertainment
  gamepad2: Gamepad2,
  dice1: Dice1,
  dice2: Dice2,
  dice3: Dice3,
  dice4: Dice4,
  dice5: Dice5,
  dice6: Dice6,
  puzzle: Puzzle,
  target: Target,

  // Tools & Crafts
  wand2: Wand2,
  palette: Palette,
  brush: Brush,
  scissors: Scissors,
  ruler: Ruler,
  compassTool: CompassTool,
  wrench: Wrench,
  hammer: Hammer,
  screwdriver: Screwdriver,
  drill: Drill,
  saw: Saw,
  pickaxe: Pickaxe,
  shovel: Shovel,
  axe: Axe,

  // Fantasy & Adventure
  sword: Sword,
  shieldIcon: ShieldIcon,
  crosshair: Crosshair,
  scope: Scope,
  bomb: Bomb,
  flame: Flame,
  snowflake: Snowflake,
  lightning: Lightning,
  tornado: Tornado,
  volcano: Volcano,
  mountain: Mountain,
  waves: Waves,

  // Celestial
  sunny: Sunny,
  lunar: Lunar,
  starIcon: StarIcon,
  comet: Comet,
  rocket: Rocket,
  satellite: Satellite,
  earth: Earth,
} as const;

const Icon = React.forwardRef<SVGSVGElement, IconProps>(
  ({ className, variant, size, name, ...props }, ref) => {
    const IconComponent = iconMap[name] as LucideIcon;

    if (!IconComponent) {
      console.warn(`Icon "${name}" not found in iconMap`);
      return null;
    }

    return (
      <IconComponent
        className={cn(iconVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    );
  }
);
Icon.displayName = "Icon";

export { Icon, iconVariants, iconMap };
export type { IconProps };
